site_name: Anki Manual
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
nav:
    - Introduction: intro.md
    - Background: background.md
    - Getting Started: getting-started.md
    - Studying: studying.md
    - Adding/Editing: editing.md
    - Card Templates: templates_intro.md
    - Field Replacements: templates_fields.md # should be subsection
    - Card Generation: templates_generation.md # should be subsection
    - Styling & HTML: templates_styling.md # should be subsection
    - Preferences: preferences.md
    - Deck Options: deck-options.md
    - Syncing with AnkiWeb: syncing.md
    - Profiles: profiles.md
    - Browsing: browsing.md
    - Filtered Decks: filtered-decks.md
    - Searching: searching.md
    - Importing: importing.md
    - Exporting: exporting.md
    - Managing Files: files.md
    - Statistics: stats.md
    - Media: media.md
    - Math & Symbols: math.md
    - Leeches: leeches.md
    - Add-ons: addons.md
    - Miscellaneous: misc.md
    - Contributing: contrib.md
    - FAQs: faqs.md
    - Resources: resources.md
