site_name: Anki Manual
site_url: https://johan456789.github.io/anki-mkdocs/
repo_url: https://github.com/johan456789/anki-mkdocs
repo_name: anki-mkdocs
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.magiclink
nav:
    - Introduction: intro.md
    - Background: background.md
    - Getting Started: getting-started.md
    - Studying: studying.md
    - Adding/Editing: editing.md
    - Card Templates:
        - Introduction: templates_/intro.md
        - Field Replacements: templates_/fields.md
        - Card Generation: templates_/generation.md
        - Styling & HTML: templates_/styling.md
    - Preferences: preferences.md
    - Deck Options: deck-options.md
    - Syncing with AnkiWeb: syncing.md
    - Profiles: profiles.md
    - Browsing: browsing.md
    - Filtered Decks: filtered-decks.md
    - Searching: searching.md
    - Importing: importing.md
    - Exporting: exporting.md
    - Managing Files: files.md
    - Statistics: stats.md
    - Media: media.md
    - Math & Symbols: math.md
    - Leeches: leeches.md
    - Add-ons: addons.md
    - Miscellaneous: misc.md
    - Contributing: contrib.md
    - FAQs: faqs.md
    - Resources: resources.md
